# Generated by Django 5.0 on 2023-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.CAXQe3AgWFel1hIzxDZ6owEsDg?w=266&h=199&c=7&r=0&o=5&dpr=1.3&pid=1.7', max_length=500),
        ),
    ]
